fixtures:
  forge_modules:
    stdlib:
      repo: puppetlabs/stdlib
    apt:
      repo: puppetlabs/apt
      ref: "7.7.1"
    translate:
      repo: puppetlabs/translate
      ref: "2.2.0"
    zypprepo:
      repo: puppet/zypprepo
